### ISSUE TITLE
TrafficReportMessage not parsing ICAO address properly

### ISSUE THREAD

**Issue by 121mhz** [apps4av/avarehelper#12]
I believe line 105 should be:
mIcaoAddress = ((((int)msg[1])&0xFF) << 16) + ((((int)(msg[2]) & 0xFF) << 8)) + ((((int)msg[3]) & 0xFF));

Your version does the bitshift prior to the AND, resulting in only the least significant byte being recorded

**Comment by apps4av** [comment]
Fixed in 3.1.0. Thanks
